services:
  ai-service:
    image: samarkinivan/ai-service:latest
    container_name: ai-service
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      APP_PORT: 8085
      MAIL_PORT: 587
      RMQ_QUEUE: 'ai-queue'
      RMQ_URL: 'amqp://host.docker.internal:5672'
    ports:
      - '8085:8085'
    depends_on:
      - ai-service-db

  ai-service-db:
    image: postgres:latest
    container_name: ai-service-db
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=SecretPassword161
      - POSTGRES_USER=user
      - POSTGRES_DB=AIDB
    ports:
      - 5432:5432
    volumes:
      - ./.meta/postgres:/var/lib/postgresql/data
